package com.yenaly.duanzile

const val PROJECT_TOKEN = "46EC8AA538DB4D76B258EB7967AD9223"

const val DUANZILE_BASE_URL = "http://tools.cretinzp.com/jokes/"

const val DECRYPT_KEY = "cretinzp**273846"

const val TO_USER_ACTIVITY_ID = "TO_USER_ACTIVITY_ID"

const val TO_USER_ACTIVITY_IS_SELF = "TO_USER_ACTIVITY_IS_SELF"

const val TO_USER_ACTIVITY_WHAT = "TO_USER_ACTIVITY_WHAT"

const val TO_TEXT_VIDEO_SPLIT_FRAGMENT = "TO_TEXT_VIDEO_SPLIT_FRAGMENT"

const val TO_DUANZI_ACTIVITY_ID = "TO_DUANZI_ACTIVITY_ID"

const val TO_FOLLOW_FAN_ACTIVITY_ID = "TO_FOLLOW_FAN_ACTIVITY_ID"
